In [3]:
#important features of pandas
# data structures
# data cleaning
# indexing and slicing
# data aggregation
# data transformation
# time series handling
# data visualization
# file i/o

In [7]:
import pandas as pd
li={
    'name':['Anjali','Rahul','Ravi','Kishan'],
    'class':[1,2,3,4]
}
up=pd.DataFrame(li)
print(up)

     name  class
0  Anjali      1
1   Rahul      2
2    Ravi      3
3  Kishan      4


In [9]:
data=[10,20,20,40,9]
series=pd.Series(data)
series

0    10
1    20
2    20
3    40
4     9
dtype: int64

In [11]:
# create a series using a custom index/label
data=[10,20,30,40,12,80]
i=['a','b','c','d','e','f']
series=pd.Series(data, index=i)
print(series)

a    10
b    20
c    30
d    40
e    12
f    80
dtype: int64


In [13]:
# create pandas series using dictionary
data={'a':10,'b':20,'c':30 ,'d':40 }
series=pd.Series(data)
print(series)

a    10
b    20
c    30
d    40
dtype: int64


In [15]:
# pandas dataframe
hi={'Name': [ 'Alice','Bob','Mary','John','Jacob'],
    'Age':[25,30,45,50,55],
    'Country':['India','India','Usa','Usa','Uk']}
df=pd.DataFrame(hi)
print(df)

    Name  Age Country
0  Alice   25   India
1    Bob   30   India
2   Mary   45     Usa
3   John   50     Usa
4  Jacob   55      Uk


In [17]:
#create pandas dataframe from a 2d numpy array
import numpy as np
arr=np.array([[10,5,20],[14,25,6],[7,18,9]])
print(arr)
df=pd.DataFrame(arr)
print(df)

[[10  5 20]
 [14 25  6]
 [ 7 18  9]]
    0   1   2
0  10   5  20
1  14  25   6
2   7  18   9


In [19]:
stu={
    'Semester':[1,2,3,4,5,6,7,8],
    'Student1':[99,98,99,99,99,99,99,99],
    'Student2':[98,99,99,99,99,99,99,99],
    'Student3':[97,99,99,99,99,99,99,99],
    'Student4':[96,99,99,99,99,99,99,99],
    'Student5':[95,99,99,99,99,99,99,99],
    'Student6':[94,99,99,99,99,99,99,99]
}
semester=[1,2,3,4,5,6,7,8]

ds=pd.DataFrame(stu,index=semester)
print(ds.to_string(index=False))



    

 Semester  Student1  Student2  Student3  Student4  Student5  Student6
        1        99        98        97        96        95        94
        2        98        99        99        99        99        99
        3        99        99        99        99        99        99
        4        99        99        99        99        99        99
        5        99        99        99        99        99        99
        6        99        99        99        99        99        99
        7        99        99        99        99        99        99
        8        99        99        99        99        99        99


In [21]:
# import data from a csv file and 
import pandas as pd
iris_df = pd.read_csv("iris.csv")
print(iris_df)

     sepal.length  sepal.width  petal.length  petal.width    variety
0             5.1          3.5           1.4          0.2     Setosa
1             4.9          3.0           1.4          0.2     Setosa
2             4.7          3.2           1.3          0.2     Setosa
3             4.6          3.1           1.5          0.2     Setosa
4             5.0          3.6           1.4          0.2     Setosa
..            ...          ...           ...          ...        ...
145           6.7          3.0           5.2          2.3  Virginica
146           6.3          2.5           5.0          1.9  Virginica
147           6.5          3.0           5.2          2.0  Virginica
148           6.2          3.4           5.4          2.3  Virginica
149           5.9          3.0           5.1          1.8  Virginica

[150 rows x 5 columns]


In [23]:
iris_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype  
---  ------        --------------  -----  
 0   sepal.length  150 non-null    float64
 1   sepal.width   150 non-null    float64
 2   petal.length  150 non-null    float64
 3   petal.width   150 non-null    float64
 4   variety       150 non-null    object 
dtypes: float64(4), object(1)
memory usage: 6.0+ KB


In [25]:
iris_df.head(10)

sepal.length  sepal.width  petal.length  petal.width variety
0           5.1          3.5           1.4          0.2  Setosa
1           4.9          3.0           1.4          0.2  Setosa
2           4.7          3.2           1.3          0.2  Setosa
3           4.6          3.1           1.5          0.2  Setosa
4           5.0          3.6           1.4          0.2  Setosa
5           5.4          3.9           1.7          0.4  Setosa
6           4.6          3.4           1.4          0.3  Setosa
7           5.0          3.4           1.5          0.2  Setosa
8           4.4          2.9           1.4          0.2  Setosa
9           4.9          3.1           1.5          0.1  Setosa

In [27]:
iris_df.describe()

sepal.length  sepal.width  petal.length  petal.width
count    150.000000   150.000000    150.000000   150.000000
mean       5.843333     3.057333      3.758000     1.199333
std        0.828066     0.435866      1.765298     0.762238
min        4.300000     2.000000      1.000000     0.100000
25%        5.100000     2.800000      1.600000     0.300000
50%        5.800000     3.000000      4.350000     1.300000
75%        6.400000     3.300000      5.100000     1.800000
max        7.900000     4.400000      6.900000     2.500000

In [29]:
iris_df[["sepal.length","petal.width"]]

sepal.length  petal.width
0             5.1          0.2
1             4.9          0.2
2             4.7          0.2
3             4.6          0.2
4             5.0          0.2
..            ...          ...
145           6.7          2.3
146           6.3          1.9
147           6.5          2.0
148           6.2          2.3
149           5.9          1.8

[150 rows x 2 columns]

In [31]:
iris_df.iloc[10:21,:]

sepal.length  sepal.width  petal.length  petal.width variety
10           5.4          3.7           1.5          0.2  Setosa
11           4.8          3.4           1.6          0.2  Setosa
12           4.8          3.0           1.4          0.1  Setosa
13           4.3          3.0           1.1          0.1  Setosa
14           5.8          4.0           1.2          0.2  Setosa
15           5.7          4.4           1.5          0.4  Setosa
16           5.4          3.9           1.3          0.4  Setosa
17           5.1          3.5           1.4          0.3  Setosa
18           5.7          3.8           1.7          0.3  Setosa
19           5.1          3.8           1.5          0.3  Setosa
20           5.4          3.4           1.7          0.2  Setosa

In [33]:
iris_df.iloc[15:21,[0,3]]

sepal.length  petal.width
15           5.7          0.4
16           5.4          0.4
17           5.1          0.3
18           5.7          0.3
19           5.1          0.3
20           5.4          0.2

In [35]:
iris_df.loc[10:20,"sepal.length":"petal.length"]

sepal.length  sepal.width  petal.length
10           5.4          3.7           1.5
11           4.8          3.4           1.6
12           4.8          3.0           1.4
13           4.3          3.0           1.1
14           5.8          4.0           1.2
15           5.7          4.4           1.5
16           5.4          3.9           1.3
17           5.1          3.5           1.4
18           5.7          3.8           1.7
19           5.1          3.8           1.5
20           5.4          3.4           1.7

In [37]:
#create dataframe with the array
data={'weight':[66,75,84,96,48,71],
      'height':[156,165,186,165,174,167]}
bmi=pd.DataFrame(data)
bmi


weight  height
0      66     156
1      75     165
2      84     186
3      96     165
4      48     174
5      71     167

In [39]:
# create a bmi column. formula: (weight(kg))/(height(m))^2
bmi["BMI"]=bmi["weight"]/(bmi["height"]/100)**2
bmi

weight  height        BMI
0      66     156  27.120316
1      75     165  27.548209
2      84     186  24.280264
3      96     165  35.261708
4      48     174  15.854142
5      71     167  25.458066

In [41]:
bmi.loc[3]=[78,np.nan,np.nan]
bmi

weight  height        BMI
0      66   156.0  27.120316
1      75   165.0  27.548209
2      84   186.0  24.280264
3      78     NaN        NaN
4      48   174.0  15.854142
5      71   167.0  25.458066

In [43]:
#insert another row with missing values
bmi.loc[5]=[np.nan,69,np.nan]
bmi

weight  height        BMI
0    66.0   156.0  27.120316
1    75.0   165.0  27.548209
2    84.0   186.0  24.280264
3    78.0     NaN        NaN
4    48.0   174.0  15.854142
5     NaN    69.0        NaN

In [45]:
#replace missing value with the mean value of that column
bmi["bmi_new"]=bmi["weight"]/(bmi["height"]/100)**2
bmi

weight  height        BMI    bmi_new
0    66.0   156.0  27.120316  27.120316
1    75.0   165.0  27.548209  27.548209
2    84.0   186.0  24.280264  24.280264
3    78.0     NaN        NaN        NaN
4    48.0   174.0  15.854142  15.854142
5     NaN    69.0        NaN        NaN

In [54]:
#DAta visualisation on iris dataset
iris_df=pd.read_csv("iris.csv")
iris_df

sepal.length  sepal.width  petal.length  petal.width    variety
0             5.1          3.5           1.4          0.2     Setosa
1             4.9          3.0           1.4          0.2     Setosa
2             4.7          3.2           1.3          0.2     Setosa
3             4.6          3.1           1.5          0.2     Setosa
4             5.0          3.6           1.4          0.2     Setosa
..            ...          ...           ...          ...        ...
145           6.7          3.0           5.2          2.3  Virginica
146           6.3          2.5           5.0          1.9  Virginica
147           6.5          3.0           5.2          2.0  Virginica
148           6.2          3.4           5.4          2.3  Virginica
149           5.9          3.0           5.1          1.8  Virginica

[150 rows x 5 columns]

In [70]:
import matplotlib.pyplot as plt
plt.hist(iris_df["sepal.length"],color="lightgreen")


(array([ 9., 23., 14., 27., 16., 26., 18.,  6.,  5.,  6.]),
 array([4.3 , 4.66, 5.02, 5.38, 5.74, 6.1 , 6.46, 6.82, 7.18, 7.54, 7.9 ]),
 <BarContainer object of 10 artists>)